In [1]:
# サンプルコード

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


# 【問題1】これまで利用してきたクラスの列挙

## 1-1. Pandas

* class DataFrame
* class Series

## 1-2. matplotlib

* class ClabelText
* class DraggableLegend
* class Figure

## 1-3. scikit-learn

* class PCA
* class LinearRegression
* class DecisionTreeClassifier

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

## 2-1. インスタンス変数

* class DataFrame
  + data
  + index
  + columns
  + dtype
  + copy

* class Figure
  + figsize
  + linewidth
  + subplotpars
  + tight_layout
  + constrained_layout
 
* class LinearRegression
  + fit_intercept
  + normalize
  + copy_X
  + n_jobs
  + positive


## 2-2. メソッド 

* class DataFrame
  + axes()
  + shape()
  + from_dict()
  + to_numpy()
  + to_dict()
  
* class Figure
  + show()
  + subplots()
  + legend()
  + subplots_adjust()
  + tight_layout()
  
* class LinearRegression
  + fit()
  + _pre_fit()



# 【問題3】標準化クラスをスクラッチで作成


In [2]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = sum(X) / len(X) 
        self.var_ = sum((X - (sum(X) / len(X)))**2) / len(X)

    
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特徴量
        """
        X_scaled = (X - self.mean_) / self.var_**0.5
        
        return X_scaled

In [3]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [4]:
# サンプルコード

class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        
        
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


# 【問題4】 四則演算を行うクラスの作成

In [5]:
class BasicCalculation():
    """
    四則演算を行うクラス
    
    Parameters
    ----------
    value : float or int
        初期値
        
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        if type(value) != int and type(value) != float:
            raise ValueError("Type Incorrect Error")
        else:
            self.value = value
            print("初期値{}が設定されました".format(self.value))

    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        
    def sub(self, value3):
        """
        受け取った引数をself.valueから差し引く
        """
        self.value -= value3
        
    def mul(self, value4):
        """
        受け取った引数をself.valueに掛け合わせる
        """
        self.value *= value4
        
    def div(self, value5):
        """
        受け取った引数でself.valueを割る
        """
        self.value /= value5


In [6]:
example = BasicCalculation(5)
print("value : {}".format(example.value))

example.add(3)
print("value : {}".format(example.value))

example.sub(2)
print("value : {}".format(example.value))

example.mul(2)
print("value : {}".format(example.value))

example.div(2)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 6
value : 12
value : 6.0
